---
- name: Install jenkins specific system packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ jenkins_debian_pkgs }}"

- name: Create jenkins folder
  file:
    path: /usr/share/jenkins
    state: directory
    owner: ubuntu

- name: Download Jenkins war file
  get_url:
    url: "{{ jenkins_war_url }}"
    dest: /usr/share/jenkins

- name: Create jenkins group
  group:
    name: "{{ jenkins_group }}"
    state: present

- name: Add the jenkins user to the group
  user:
    name: "{{ jenkins_user }}"
    append: yes
    groups: "{{ jenkins_group }}"

- name: Create init.groovy.d
  file:
    path: "{{ jenkins_home }}/init.groovy.d"
    state: directory
    owner: ubuntu

- name: Create utils
  file:
    path: "{{ jenkins_home }}/utils"
    state: directory
    owner: ubuntu

- name: Create plugins
  file:
    path: "{{ jenkins_home }}/plugins"
    state: directory
    owner: ubuntu

- name: Create folder for git repositories
  file:
    path: /git
    state: directory
    owner: ubuntu

- name: Download jenkins-configuration repo
  git:
      repo: "{{ jenkins_configuration_git_url }}"
      dest: /git/jenkins-configuration

- name: Make plugins directory
  file:
    path: "{{ jenkins_home }}/plugins"
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"

- name: Download Jenkins plugins
  get_url:
    url: "http://updates.jenkins-ci.org/download/plugins/{{ item.name }}/{{ item.version }}/{{ item.name }}.hpi"
    dest: "/tmp/{{ item.name }}_{{ item.version }}"
  with_items: "{{ jenkins_pinned_plugins }}"
  register: jenkins_plugin_downloads
  tags:
    - install
    - install:base
    - install:plugins

- name: Install Jenkins plugins
  command: "cp {{ item.dest }} {{ jenkins_home }}/plugins/{{ item.item.name }}.hpi"
  with_items: "{{ jenkins_plugin_downloads.results }}"
  when: item.changed

- name: Set Jenkins plugin permissions
  file:
    path: "{{ jenkins_home }}/plugins/{{ item.item.name }}.hpi"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    mode: "0644"
  with_items: "{{ jenkins_plugin_downloads.results }}"
  when: item.changed

- name: Create plugin pin files
  command: "touch {{ jenkins_home }}/plugins/{{ item.name }}.jpi.pinned"
  args:
    creates: "{{ jenkins_home }}/plugins/{{ item.name }}.jpi.pinned"
  with_items: "{{ jenkins_pinned_plugins }}"

- name: Copy desired jenkins-configuration scripts to $JENKINS_HOME/init.groovy.d directory
  copy:
    src: "/git/jenkins-configuration/src/main/groovy/{{ item }}"
    dest: "{{ jenkins_home }}/init.groovy.d/"
    remote_src: true
  with_items: "{{ jenkins_configuration_scripts }}"

- name: Copy config documents
  copy:
    src: "{{ jenkins_config_templates }}/*"
    dest: "{{ jenkins_config_files }}/init-configs/"

- name: Set owner for jenkins_home
  file:
    path: "{{ jenkins_home }}"
    recurse: yes
    state: directory
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
